# Generated by Django 4.0.4 on 2022-05-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
